### ISSUE TITLE
Install Windows 10?

### ISSUE THREAD

**Issue by hugodupan** [Chiang97912/bet365.com#10]
Trying to install, I'm having the problem below:

`Running setup.py install for Twisted ... error
Exception:
Traceback (most recent call last):
  File "c:\users\hugo.borges\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 9: invalid continuation
byte
Como resolver?
Traduzir do: Inglês
441/5000
Trying to install, I'm having the problem below:
Running setup.py install for Twisted ... error
Exception:
Traceback (most recent call last):
   File "c: \ users \ hugo.borges \ appdata \ local \ programs \ python \ python36-32 \ lib \ site-packages \ pip \ compat \ __ init__.py", line 73, in console_to_str
     return s.decode (sys .__ stdout __. encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 9: invalid continuation
byte`

How to solve?

**Comment by hugodupan** [comment]
I was able to install with git-bash.
After doing the procedures mentioned in [README](https://github.com/Chiang97912/bet365.com/blob/master/README.md), I had to install a package called 'pyOpenSSL': `pip install pyOpenSSL`
And run by calling the **Phyton** command and not **Python3** (_I believe it is Windows_).
